### PR TITLE
Multi exec

### PR DESCRIPTION
**Pull request by BaReinhard**
Allows for the functionality of backing up original files and allows for uninstallation of all or specific features. The uninstallation process, removes files copied via the install script, removes system daemons, and removes all dependencies added during the install. For the dependencies added via apt-get, there needs to be a way to check if they were previously installed or not, otherwise it may be removing existing dependencies and breaking the functionality of the RPI after uninstall.

### CODE REVIEW

**Comment by BaReinhard** [comment]
> For the dependencies added via apt-get, there needs to be a way to check if they were previously installed or not, otherwise it may be removing existing dependencies and breaking the functionality of the RPI after uninstall.

Dependencies are now checked before installation, if the dependency is met the script will move to the next dependency. If the dependency is not met, it will install the dependency and then add the dependency name to $SSPARI_PATH/installed_deps. 

Upon on uninstallation, the apt_uninstall will check each dependency again the installed_deps file, if it is present it will uninstall the dependency, otherwise the dependency will be left installed.

**Comment by Dmac9244** [comment]
Hey, BaReinhard, it's great that you're working on this again! I'm not sure where to say this, so I guess I'll say it here, where you seem to have been working most recently: I noticed in your README that you still say that you haven't tested the HiFiBerry Pro DAC+. If it helps, I'm still running the version of your script from the summer, and my DAC+ is working great with Bluetooth and Airplay. It's running on an RPi 1 B+ model, with ethernet and a Bluetooth dongle. If there are any other features you want me to test, or if you want me to test on the latest versions of the script, I can try to do that over the weekend, when I have more time.

By the way, thanks for sharing your awesome, convenient script, and spending the time to perfect it!

**Comment by BaReinhard** [comment]
Hey @Dmac9244 thanks! I am glad you've been using it. Awesome to hear it works with the DAC+, I have a few other DAC's I need to test with.

I hope to test this newest script tonight, but I can't say for certain.

Any testing I am always appreciative. I think with the latest changes with updated logging, it should be easier to pin point any errors as well as rerun the install script without having to flash a new sdcard on each error encountered.

**Comment by Dmac9244** [comment]
@BaReinhard You're welcome! I'll see what I can do to help; I'm not a very experienced programmer, debugger, or tester.

**Comment by BaReinhard** [comment]
@Dmac9244 when I started this project I wasn't much of either one of those either haha. It's most telling by when I first started adding features, now the code is a bit better, but I'm still not a great bash programmer. Although, I have progressed quite well at fixing errors or at least knowing where to look for answers.

**Comment by BaReinhard** [comment]
change the install of snapclient and snapserver to downloading and dpkging binary files to save time on compilation. REF: https://gist.github.com/totti2/41ed90feb1eb5838cc6a789d2b2dd5a7

**Comment by BaReinhard** [comment]
Installation of snapclient and server works great! Will need feedback from endusers who choose this for card numbers for snapclient for different DACS, iqaudio dac zero uses 6, bcm uses 2 or 3.

**Pull request merged**
